
name: Setup Node 16
description: Setup Node 16
runs:
  using: composite
  steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 16
        registry-url: https://registry.npmjs.org
