name: Publish stable
on:
  workflow_dispatch:
    inputs:
      slicemachine/adapter-next:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slicemachine/adapter-nuxt:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slicemachine/adapter-nuxt2:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slicemachine/adapter-sveltekit:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slicemachine/init:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slicemachine/manager:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slicemachine/plugin-kit:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      slice-machine-ui:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
      start-slicemachine:
        default: decline
        type: choice
        options:
          - major
          - minor
          - patch
          - decline
jobs:
  publish-stable:
    if: 'startsWith(github.ref, ''refs/heads/main'')'
    name: Publish stable
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: yarn install
      - name: Build essentials
        uses: ./.github/actions/build-essential
      - name: Run publish script
        env:
          SENTRY_AUTH_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN }}'
          YARN_NPM_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
        run: |
          inputs=$(echo '${{ toJSON(github.event.inputs) }}' | jq -c)
          package_names=$(echo $inputs | jq -r 'keys | .[]')
          specifiers=""
          for package in $package_names; do
            package_release_type=$(echo $inputs | jq -r --arg k "$package" '.[$k]')
            if 
            if ["$package_name == slicemachine/*" && "package_release_type" != "decline"]; then 
              specifiers+="@$package:$package_release_type "
            elif [ "package_release_type" != "decline" ]; then
              specifiers+="$package:$package_release_type "
            fi
          done
          yarn publish stable --dry-run $specifiers